python train_unet_MiDSS_DC_v2.py --dataset prostate --lb_domain 1 --lb_num 20 --save_name MIDSS_DC_NEW_DEBUG_D1 --gpu 3 --save_model --overwrite --dc_parts 5 --dc_distance_mode sqrt_prod --enable_piecewise_tau --tau_min 0.85 --tau_max 0.95 --expend_test_steps_interval 300 --expend_max_steps 1200 --expend_test_samples 128 --expand_conf_threshold 0.75 --curr_conf_threshold 0.75 --curr_conf_samples 128 --conf_strategy robust --use_symgd --symgd_mode full --llm_model GPT5 --describe_nums 80 --use_freq_aug --max_iterations 30000 --use_next_conf --use_curr_conf --warmup --warmup_period 2000    

python train_unet_MiDSS_DC_v2.py --dataset prostate --lb_domain 6 --lb_num 20 --save_name MIDSS_DC_NEW_DEBUG_D6 --gpu 2 --save_model --overwrite --dc_parts 5 --dc_distance_mode sqrt_prod --enable_piecewise_tau --tau_min 0.85 --tau_max 0.95 --expend_test_steps_interval 300 --expend_max_steps 1200 --expend_test_samples 128 --expand_conf_threshold 0.75 --curr_conf_threshold 0.75 --curr_conf_samples 128 --conf_strategy robust --use_symgd --symgd_mode full --llm_model GPT5 --describe_nums 80 --use_freq_aug --max_iterations 30000 --use_next_conf --use_curr_conf --warmup --warmup_period 2000    


python train_unet_MiDSS_DC_v2.py --dataset prostate --lb_domain 1 --lb_num 20 --save_name MIDSS_DC_NEW_DEBUG_D1_2 --gpu 3 --save_model --overwrite --dc_parts 5 --dc_distance_mode sqrt_prod --enable_piecewise_tau --tau_min 0.85 --tau_max 0.95 --expend_test_steps_interval 300 --expend_max_steps 1200 --expend_test_samples 128 --expand_conf_threshold 0.75 --curr_conf_threshold 0.75 --curr_conf_samples 128 --conf_strategy dice --no_symgd --llm_model GPT5 --describe_nums 80 --use_freq_aug --max_iterations 30000 --use_next_conf --use_curr_conf --warmup --warmup_period 2000    

python train_unet_MiDSS_DC_v2.py --dataset prostate --lb_domain 1 --lb_num 20 --save_name MIDSS_DC_NEW_DEBUG_D1_3 --gpu 2 --save_model --overwrite --dc_parts 5 --dc_distance_mode prototype --enable_piecewise_tau --tau_min 0.85 --tau_max 0.95 --expend_test_steps_interval 300 --expend_max_steps 1200 --expend_test_samples 128 --expand_conf_threshold 0.75 --curr_conf_threshold 0.75 --curr_conf_samples 128 --conf_strategy dice --no_symgd --llm_model GPT5 --describe_nums 80 --use_freq_aug --max_iterations 30000 --use_next_conf --use_curr_conf --warmup --warmup_period 2000    


screen -dmS MIDSS_DC_DEBUG_D1 bash -c "python train_unet_MiDSS_DC_v2.py --dataset prostate --lb_domain 1 --lb_num 20 --save_name MIDSS_DC_NEW_DEBUG_D1 --gpu 3 --save_model --overwrite --dc_parts 5 --dc_distance_mode sqrt_prod --enable_piecewise_tau --tau_min 0.85 --tau_max 0.95 --expend_test_steps_interval 300 --expend_max_steps 1200 --expend_test_samples 128 --expand_conf_threshold 0.75 --curr_conf_threshold 0.75 --curr_conf_samples 128 --conf_strategy robust --use_symgd --symgd_mode full --llm_model GPT5 --describe_nums 80 --use_freq_aug --use_next_conf --use_curr_conf --warmup --warmup_period 2000 "

screen -dmS MIDSS_DC_DEBUG_D6 bash -c "python train_unet_MiDSS_DC_v2.py --dataset prostate --lb_domain 6 --lb_num 20 --save_name MIDSS_DC_NEW_DEBUG_D6 --gpu 2 --save_model --overwrite --dc_parts 5 --dc_distance_mode sqrt_prod --enable_piecewise_tau --tau_min 0.85 --tau_max 0.95 --expend_test_steps_interval 300 --expend_max_steps 1200 --expend_test_samples 128 --expand_conf_threshold 0.75 --curr_conf_threshold 0.75 --curr_conf_samples 128 --conf_strategy robust --use_symgd --symgd_mode full --llm_model GPT5 --describe_nums 80 --use_freq_aug  --use_next_conf --use_curr_conf --warmup --warmup_period 2000 "



screen -dmS MIDSS_DC_D1 bash -c "python train_unet_MiDSS_DC_v2.py --dataset prostate --lb_domain 1 --lb_num 20 --save_name MIDSS_DC_NEW_D1 --gpu 3 --save_model --overwrite --dc_parts 5 --dc_distance_mode sqrt_prod --enable_piecewise_tau --tau_min 0.85 --tau_max 0.95 --expend_test_steps_interval 300 --expend_max_steps 1200 --expend_test_samples 64 --expand_conf_threshold 0.7 --curr_conf_threshold 0.7 --curr_conf_samples 128 --conf_strategy robust --use_symgd --symgd_mode full --llm_model GPT5 --describe_nums 80 --use_freq_aug --use_next_conf --use_curr_conf --warmup --warmup_period 2000 "

