python train_unet_only_UCP_DC_v2.py   --dataset prostate   --lb_domain 6   --lb_num 20   --save_name Unet_UCP_symGD_5_DC_v2_d6   --gpu 0   --save_model   --overwrite   --dc_parts 5   --expend_test_steps_interval 250   --expend_max_steps 2000   --expand_conf_threshold 0.6   --expand_conf_weight 1.0   --expend_test_samples 32   --curr_conf_weight 1.0   --curr_conf_threshold 0.75   --curr_conf_samples 64   --ul_weight 1.0   --lu_weight 1.0   --cons_weight 1.0   --llm_model gemini   --describe_nums 80 

# 配置基本测试1

screen -dmS unet-ucp-symGD-DC-5-prostate-d6 bash -c "python train_unet_only_UCP_DC_v2.py   --dataset prostate   --lb_domain 6   --lb_num 20   --save_name Unet_UCP_symGD_5_DC_v2_d6   --gpu 0   --save_model   --overwrite   --dc_parts 5   --expend_test_steps_interval 250   --expend_max_steps 2000   --expand_conf_threshold 0.6   --expand_conf_weight 1.0   --expend_test_samples 32   --curr_conf_weight 1.0   --curr_conf_threshold 0.75   --curr_conf_samples 64   --ul_weight 1.0   --lu_weight 1.0   --cons_weight 1.0   --llm_model gemini   --describe_nums 80 "

screen -dmS unet-ucp-symGD-DC-5-prostate-d5 bash -c "python train_unet_only_UCP_DC_v2.py   --dataset prostate   --lb_domain 5   --lb_num 20   --save_name Unet_UCP_symGD_5_DC_v2_d5   --gpu 0   --save_model   --overwrite   --dc_parts 5   --expend_test_steps_interval 250   --expend_max_steps 2000   --expand_conf_threshold 0.6   --expand_conf_weight 1.0   --expend_test_samples 32   --curr_conf_weight 1.0   --curr_conf_threshold 0.75   --curr_conf_samples 64   --ul_weight 1.0   --lu_weight 1.0   --cons_weight 1.0   --llm_model gemini   --describe_nums 80 "

screen -dmS unet-ucp-symGD-DC-5-prostate-d4 bash -c "python train_unet_only_UCP_DC_v2.py   --dataset prostate   --lb_domain 4   --lb_num 20   --save_name Unet_UCP_symGD_5_DC_v2_d4   --gpu 0   --save_model   --overwrite   --dc_parts 5   --expend_test_steps_interval 250   --expend_max_steps 2000   --expand_conf_threshold 0.6   --expand_conf_weight 1.0   --expend_test_samples 32   --curr_conf_weight 1.0   --curr_conf_threshold 0.75   --curr_conf_samples 64   --ul_weight 1.0   --lu_weight 1.0   --cons_weight 1.0   --llm_model gemini   --describe_nums 80 "

screen -dmS unet-ucp-symGD-DC-5-prostate-d3 bash -c "python train_unet_only_UCP_DC_v2.py   --dataset prostate   --lb_domain 3   --lb_num 20   --save_name Unet_UCP_symGD_5_DC_v2_d3   --gpu 1   --save_model   --overwrite   --dc_parts 5   --expend_test_steps_interval 250   --expend_max_steps 2000   --expand_conf_threshold 0.6   --expand_conf_weight 1.0   --expend_test_samples 32   --curr_conf_weight 1.0   --curr_conf_threshold 0.75   --curr_conf_samples 64   --ul_weight 1.0   --lu_weight 1.0   --cons_weight 1.0   --llm_model gemini   --describe_nums 80 "

screen -dmS unet-ucp-symGD-DC-5-prostate-d2 bash -c "python train_unet_only_UCP_DC_v2.py   --dataset prostate   --lb_domain 2   --lb_num 20   --save_name Unet_UCP_symGD_5_DC_v2_d2   --gpu 1   --save_model   --overwrite   --dc_parts 5   --expend_test_steps_interval 250   --expend_max_steps 2000   --expand_conf_threshold 0.6   --expand_conf_weight 1.0   --expend_test_samples 32   --curr_conf_weight 1.0   --curr_conf_threshold 0.75   --curr_conf_samples 64   --ul_weight 1.0   --lu_weight 1.0   --cons_weight 1.0   --llm_model gemini   --describe_nums 80 "

screen -dmS unet-ucp-symGD-DC-5-prostate-d1 bash -c "python train_unet_only_UCP_DC_v2.py   --dataset prostate   --lb_domain 1   --lb_num 20   --save_name Unet_UCP_symGD_5_DC_v2_d1   --gpu 1   --save_model   --overwrite   --dc_parts 5   --expend_test_steps_interval 250   --expend_max_steps 2000   --expand_conf_threshold 0.6   --expand_conf_weight 1.0   --expend_test_samples 32   --curr_conf_weight 1.0   --curr_conf_threshold 0.75   --curr_conf_samples 64   --ul_weight 1.0   --lu_weight 1.0   --cons_weight 1.0   --llm_model gemini   --describe_nums 80 "


screen -dmS unet-ucp-symGD-DC-5-prostate-d6-v2 bash -c "python train_unet_only_UCP_DC_v2.py   --dataset prostate   --lb_domain 6   --lb_num 20   --save_name Unet_UCP_symGD_5_DC_v2_d6_v2   --gpu 2   --save_model   --overwrite   --dc_parts 5   --expend_test_steps_interval 250   --expend_max_steps 3000   --expand_conf_threshold 0.6   --expand_conf_weight 1.0   --expend_test_samples 32   --curr_conf_weight 1.0   --curr_conf_threshold 0.75   --curr_conf_samples 64   --ul_weight 1.0   --lu_weight 1.0   --cons_weight 1.0   --llm_model gemini   --describe_nums 80 --warmup"


screen -dmS unet-ucp-symGD-DC-5-prostate-d6-v3 bash -c "python train_unet_only_UCP_DC_v2.py   --dataset prostate   --lb_domain 6   --lb_num 20   --save_name Unet_UCP_symGD_5_DC_v2_d6_v3   --gpu 2   --save_model   --overwrite   --dc_parts 5   --expend_test_steps_interval 250   --expend_max_steps 3000   --expand_conf_threshold 0.6   --expand_conf_weight 1.0   --expend_test_samples 32   --curr_conf_weight 1.0   --curr_conf_threshold 0.75   --curr_conf_samples 64   --ul_weight 1.0   --lu_weight 1.0   --cons_weight 0.0   --llm_model gemini   --describe_nums 80 --warmup"


screen -dmS unet-ucp-symGD-DC-5-prostate-d6-v4 bash -c "python train_unet_only_UCP_DC_v2.py   --dataset prostate   --lb_domain 6   --lb_num 20   --save_name Unet_UCP_symGD_5_DC_v2_d6_v4   --gpu 3   --save_model   --overwrite   --dc_parts 5   --expend_test_steps_interval 250   --expend_max_steps 5000   --expand_conf_threshold 0.6   --expand_conf_weight 1.0   --expend_test_samples 32   --curr_conf_weight 1.0   --curr_conf_threshold 0.75   --curr_conf_samples 64   --ul_weight 1.0   --lu_weight 1.0   --cons_weight 1.0   --llm_model gemini   --describe_nums 80 --warmup"

screen -dmS unet-ucp-symGD-DC-5-prostate-d6-v5 bash -c "python train_unet_only_UCP_DC_v2.py   --dataset prostate   --lb_domain 6   --lb_num 20   --save_name Unet_UCP_symGD_5_DC_v2_d6_v5   --gpu 3   --save_model   --overwrite   --dc_parts 5   --expend_test_steps_interval 250   --expend_max_steps 5000   --expand_conf_threshold 0.6   --expand_conf_weight 1.0   --expend_test_samples 64   --curr_conf_weight 1.0   --curr_conf_threshold 0.75   --curr_conf_samples 128   --ul_weight 1.0   --lu_weight 1.0   --cons_weight 1.0   --llm_model gemini   --describe_nums 80 --warmup"


screen -dmS unet-ucp-symGD-DC-5-prostate-d6-v6 bash -c "python train_unet_only_UCP_DC_v2.py   --dataset prostate   --lb_domain 6   --lb_num 20   --save_name Unet_UCP_symGD_5_DC_v2_d6_v6   --gpu 3   --save_model   --overwrite   --dc_parts 5   --expend_test_steps_interval 300   --expend_max_steps 5000   --expand_conf_threshold 0.6   --expand_conf_weight 1.0   --expend_test_samples 128   --curr_conf_weight 0.0   --curr_conf_threshold 0.75   --curr_conf_samples 256   --ul_weight 1.0   --lu_weight 1.0   --cons_weight 0.0   --llm_model GPT5   --describe_nums 80 --warmup"